### PR TITLE
Update Tutorial Container for Spack v0.15.1

### PR DESCRIPTION
**Pull request by zackgalbreath**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@tgamblin This is where we're currently iterating on the build of the tutorial container, do you want to have a look at the `spack.yaml` and let us know if there are packages or compilers you want to change?

This would have gone more smoothly, but the pipeline workflow changed a little since we last used this, and also support for compiler bootstrapping pipelines has slipped again, see [here](https://github.com/spack/spack/pull/17536) for an entry point into the gory details.

**Comment by scottwittenburg** [comment]
Pipeline was proceeding ok, but hit a snag building `adept-utils`:

```
1 error found in build log:
     22      IN_LIST will be interpreted as an operator when the policy is set 
           to NEW.
     23      Since the policy is not set the OLD behavior will be used.
     24    Call Stack (most recent call first):
     25      CMakeLists.txt:22 (find_package)
     26    This warning is for project developers.  Use -Wno-dev to suppress it
           .
     27    
  >> 28    CMake Error at /builds/scott/spack-tutorial-container/spack/opt/spac
           k/linux-ubuntu18.04-x86_64/gcc-7.5.0/boost-1.73.0-qzr23mk4jzlnkdfh4m
           rncz5lvpp67z2r/lib/cmake/Boost-1.73.0/BoostConfig.cmake:240 (if):
     29      if given arguments:
     30    
     31        "ALL" "IN_LIST" "Boost_FIND_COMPONENTS"
     32    
     33      Unknown arguments specified
     34    Call Stack (most recent call first):
```

The quickest thing I can think to try to use an older version of `boost`.

**Comment by tgamblin** [comment]
I think for the tutorial container we have to ensure that spack out of the box will use the binary images.  Or update the tutorial. Should I make a new version of adept-utils? I can do that in a point release. Or should we pick a better package for the packaging example? @becker33

**Comment by scottwittenburg** [comment]
> I think for the tutorial container we have to ensure that spack out of the box will use the binary images

Yes, that makes sense for sure.  Updating `adept-utils` makes sense to me, and I can handle that and just get your review on it if you like.

**Comment by becker33** [comment]
I agree that updating adept-utils for a quick v0.15.2 is the right answer for this.

**Comment by becker33** [comment]
Eventually we'll need to update the "new" version of gcc to be more recent than 8.3.0, but I don't think there's any need to do that for this iteration.

**Comment by scottwittenburg** [comment]
> Eventually we'll need to update the "new" version of gcc to be more recent than 8.3.0

Yeah, makes sense.  If you know what version you'd prefer, I canb always just start a pipeline to try it out and see how bad it's going to be.

**Comment by becker33** [comment]
I think we originally chose 8.3.0 because it was newest at the time, if you can kick off a build with 10.1.0 and see how bad that is that would be great.

**Comment by scottwittenburg** [comment]
> Should I make a new version of adept-utils? 

Not sure I did what you were thinking, but I took a stab at it [here](https://github.com/spack/spack/pull/17560).

**Comment by becker33** [comment]
@scottwittenburg is the issue that boost doesn't build or that it adept-utils doesn't build with it properly? It looks like boost isn't building, so maybe the fix should be to change the preferred version of boost instead of changing the adept-utils package.

**Comment by tgamblin** [comment]
@becker33: as long as the preferred version of boost is the one the tutorial will resolve, I think we're good.  I was thinking the best options would be:

1. make `adept-utils` work with `boost`
2. restrict `adpt-utils` `boost` version

but if the problem is really with boost, making boost work seems like the fix

**Comment by scottwittenburg** [comment]
> 2\. restrict `adpt-utils` `boost` version

That's the approach I took, I made a PR for it and linked it in a comment above.  I was just about to add that the to the `v0.15.2` project.

**Comment by tgamblin** [comment]
I think other things depend on boost, though, so this may not be enough.

**Comment by scottwittenburg** [comment]
> I think other things depend on boost, though, so this may not be enough.

Something else must, indeed, depend on `boost`.  But is it a big deal?  I took out the env change that pinned `boost` to `1.72.0` and instead pointed the CI pipeline to a branch of spack with the `adept-utils` patch.  Now the pipeline is building with two versions of `boost`, both `1.72.0` and `1.73.0`.  Is that ok?

**Comment by becker33** [comment]
If `boost@1.73.0` isn't breaking anything in the tutorial container other than `adept-utils`, then that should be fine.

**Comment by tgamblin** [comment]
we can even use it as an example of an old unmaintained package (that I wrote) that needs an old boost version 🤷

**Comment by scottwittenburg** [comment]
> we can even use it as an example of an old unmaintained package (that I wrote) that needs an old boost version 🤷

I love  a positive outlook 😄 

FYI, I'm using a spack branch with a handful of patches needed to get compiler bootstrapping working again.  I think they're all represented in PRs which I've added to the 0.15.2 project.  One of them ([#17563](https://github.com/spack/spack/pull/17563)) may be controversial, so I'm hoping to get someone to look at it and let me know the likelihood of it making the release.

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
