### PR TITLE
Automate container build workflow

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@tgamblin I think we're pretty close here, you could probably start reviewing this.  I've added a bunch of documentation, and I have re-run the pipeline (successfully) with a signing key matching the `public.key` I added to the repo.  I've set up the DockerHub autobuild, but have yet to test it.  I'll see if I can try it on this branch instead of waiting until we push to master or create a tag.

https://gitlab.spack.io/scott/spack-tutorial-container/pipelines/229

**Comment by scottwittenburg** [comment]
fyi @opadron

**Comment by scottwittenburg** [comment]
It's kind of cool that you get a check on your PR if you have Dockerhub attempt to build against your PR branch.  But this isn't really useful given the workflow we have put together here, as we need the gitlab pipeline to have completed so the mirror actually has all the binaries we want to copy into the image.

**Comment by opadron** [comment]
When child pipelines land, will the child be considered part of the whole?  Will Gitlab CI wait for the child pipeline to complete before giving a PR the green checkmark?  I'm guessing it's going to depend on how the child pipelines feature is implemented.

In any case, it might be a good idea to implement our own status check for PR testing, and generate a job that sends the "all good" message at the end of the pipeline, or one that sends the "check failed" message that only runs in case of a job failure.  I haven't looked too deep into Github's API for this, but I have to imagine it exists and we could use it.  That would be a sure-fire way to implement a check that comes back green only when the whole pipeline completes successfully.

Just a thought.  I'm not suggesting this be tackled for this PR.

Other than that, the docs and everything else look good! :+1:

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
